server:
  port: 9021
spring:
  application:
    name: zookeeper-client-demo
  # zookeeper client config
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181




logging:
  level:
    root: debug
