server:
  port: 9011

spring:
  application:
    name: eureka-client-demo  # 服务名

# eureka client config
eureka:
  client:
    service-url:
      defaultZone: http://nullpoint:eureka@localhost:8761/eureka/

# actuator config
management:
  endpoints:
    web:
      exposure:
        include: ["*"]
  endpoint:
    health:
      show-details: always